import { Geist, Geist_Mono } from "next/font/google";
import { DownloadCountProvider } from "@/context/DownloadCountContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "StreamStorm",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <DownloadCountProvider>
                    <Header />
                        {children}
                    <Footer />
                </DownloadCountProvider>
            </body>
        </html>
    );
}
